# FILES
defaults:  # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade_maxsim
  - train/data: msmarco
  - train/model: splade_from_distilbert
  ############## INDEX ###################################
  - index: toy
  ############## RETRIEVE ################################
  - retrieve_evaluate: toy
  ############### FLOPS ##################################
  - flops: toy

# Direct PARAMETER setting
config:  # to be provided for each run
  checkpoint_dir: "/scratch/lamdo/splade_maxsim_ckpts/splade_maxsim_150k_lowregv5/debug/checkpoint"
  index_dir: "/scratch/lamdo/splade_maxsim_ckpts/splade_maxsim_150k_lowregv5/debug/index"
  out_dir: "/scratch/lamdo/splade_maxsim_ckpts/splade_maxsim_150k_lowregv5/debug/out"
  fp16: true