# FILES
defaults:  # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: splade_maxsim
  - train/data: distil_from_ensemble
  - train/model: splade_from_distilbert
  ############## INDEX ###################################
  - index: toy
  ############## RETRIEVE ################################
  - retrieve_evaluate: toy
  ############### FLOPS ##################################
  - flops: toy

# Direct PARAMETER setting
config:  # to be provided for each run
  loss: DistilMarginMSEv2
  regularizer:
    FLOPS:
      lambda_q: 0.1
      lambda_d: 0.08
      T: 50000
      targeted_rep: rep
      reg: FLOPS
  checkpoint_dir: "/scratch/lamdo/splade_maxsim_ckpts/splade_maxsim_150k_lowregv2_ensembledistil/debug/checkpoint"
  index_dir: "/scratch/lamdo/splade_maxsim_ckpts/splade_maxsim_150k_lowregv2_ensembledistil/debug/index"
  out_dir: "/scratch/lamdo/splade_maxsim_ckpts/splade_maxsim_150k_lowregv2_ensembledistil/debug/out"
  fp16: true