# FILES
defaults:  # (these specify which config FILES to use)
  ############## TRAIN ###################################
  - train/config: phrase_splade
  - train/data: phrase_splade
  - train/model: phrase_splade #splade_pretrain_from_distilbert
  ############## INDEX ###################################
  - index: toy
  ############## RETRIEVE ################################
  - retrieve_evaluate: toy
  ############### FLOPS ##################################
  - flops: toy

# Direct PARAMETER setting
config:  # to be provided for each run
  checkpoint_dir: "/scratch/lamdo/phrase_splade_checkpoints/phrase_splade_31/debug/checkpoint"
  index_dir: "/scratch/lamdo/phrase_splade_checkpoints/phrase_splade_31/debug/index"
  out_dir: "/scratch/lamdo/phrase_splade_checkpoints/phrase_splade_31/debug/out"
  fp16: false